use investidura;
go

select * from CALENDARIO;
go

use empleados;
go

select * from DATOS;
go

INSERT INTO DATOS(NOMBRE, CARGO, EDAD, FECHA)
VALUES('FRANCISCO','SOPORTE', 48, GETDATE());
GO
select * from DATOS_EMP;
GO
 
 INSERT INTO DATOS_EMP(NOMBRE, CARGO, EDAD)
 VALUES('JUAN YUM','SEGURIDAD',80);
 GO

SELECT * FROM DATOS_EMPLEADO;
GO

SELECT * FROM DATOS_EMPLEADOS;
GO

SELECT * FROM DATOS_EMPLEADOS2;
GO
INSERT INTO DATOS_EMPLEADOS2(EDAD,NOMBRE, CARGO)
VALUES(26, 'RAFAEL','ADMINISTRADOR DE REDES');
GO

SELECT * FROM DATOS_EMPLEADOSS;
GO

SELECT * FROM DATOS_EMPLEADOTRES;
GO

SELECT * FROM empleados.dbo.DATOS;
GO

select * from sys. tables;
go

