CREATE DATABASE INVESTIDURA;
GO

USE INVESTIDURA;
GO

CREATE TABLE CALENDARIO(
ID bigint identity (1000000,1) primary key,
FECHA DATETIME,
LUGAR VARCHAR(100) NOT NULL,
MODALIDAD VARCHAR(50) NOT NULL,
APERTURA VARCHAR(50) NOT NULL
);
GO

SELECT * FROM CALENDARIO;
GO

INSERT INTO CALENDARIO(FECHA, LUGAR, MODALIDAD, APERTURA)
VALUES(GETDATE()+30,'UASD-SANJUAN', 'VIRTUAL', '14 DE ABRIL DEL 2023');
GO

INSERT INTO CALENDARIO(FECHA, LUGAR, MODALIDAD, APERTURA)
VALUES(GETDATE()+60,'UASD-SANTIAGO', 'PRESENCIAL', '24 DE NOVIEMBRE DEL 2024');
GO

UPDATE CALENDARIO SET FECHA=GETDATE(); 
GO